### ISSUE TITLE
[Documentation] Could the main README briefly explain how this is detected via the python code? Does not have to be a long explanation, just the main gist of how it works. 

### ISSUE THREAD

**Issue by rubyFeedback** [daspartho/SpotiByeAds#1]
[Documentation] Could the main README briefly explain how this is detected via the python code?

Does not have to be a long explanation, just the main gist of how it works. That way people can
understand which part notices when an ad is played. For instance I presently don't know the
spotify API so this would be helpful. Thank you for potentially considering and reading this
issue request.

**Comment by daspartho** [comment]
Sure dude. I'll do that, it will be really helpful for begginers.

**Comment by WarpWing** [comment]
> Sure dude. I'll do that, it will be really helpful for begginers.

Hi! I'm WarpWing. If you want, I could remake the README for you? Actually, let me do it and send you a PR if you like it

**Comment by Bomberus** [comment]
Essentially it uses the Spotify API to check what track is currently played. Ads have a specific name (ad).

**Comment by daspartho** [comment]
Hey WarpWing! I assigned it to you as you said, just send me a PR. Good luck mate 👍

**Comment by WarpWing** [comment]
> Hey WarpWing! I assigned it to you as you said, just send me a PR. Good luck mate +1

Thanks! Should have it to you soon!
