### ISSUE TITLE
Use environment variables for secrets

### ISSUE THREAD

**Issue by rayz** [daspartho/SpotiByeAds#14]
https://github.com/daspartho/SpotiByeAds/blob/ae073ff47778c70850b23f6302bedc9d25331e8b/main.py#L59-L62

https://github.com/theskumar/python-dotenv `python-dotenv` can be an option. Just need to create a `.env` file and load the environment variables.

**Comment by lykkjur** [comment]
This kinda seems unnecessary ngl. End users won't be making PRs, so there's no danger of anyone's credentials being leaked. Anyone who does manage to leak their stuff in a commit probably shouldn't be contributing...

**Comment by airD173** [comment]
I agree. It makes much more sense just to save it to a JSON as it already is.
