### ISSUE TITLE
PATH variable gives a syntax error

### ISSUE THREAD

**Issue by 303x** [daspartho/SpotiByeAds#15]
Change the string to a raw string
Like so:
PATH = 'C:\Users\USERNAME\AppData\Roaming\Spotify'
to
PATH = r'C:\Users\USERNAME\AppData\Roaming\Spotify'

**Comment by daspartho** [comment]
yep use raw string as mentioned above

**Comment by ceceba223** [comment]
This is a really simple fix @daspartho should i open a PR just for this?

**Comment by daspartho** [comment]
Yeah that will be good

**Comment by ceceba223** [comment]
ok i'm on it

**Comment by ceceba223** [comment]
As far as i can tell this issue got fixed with the implementation of automatic Path detection

**Comment by daspartho** [comment]
Ohh yeah right 
i'll close this then
