### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by daspartho** [daspartho/SpotiByeAds#18]
Can someone volunteer to make a installation guide for those who are not experienced with programming so that will be the go-to on how to use this script.

**Comment by ceceba223** [comment]
This should probably include an installation guide for python, right?

**Comment by daspartho** [comment]
Yeah
Like the guide should be like a newcomer can use the script without any issues

**Comment by airD173** [comment]
I'll try forking it and writing documentation in the GitHub wiki. However, since this is my first time doing anything like this, someone else should write some documentation too, as I'll likely fail.

**Comment by airD173** [comment]
Actually, GitHub doesn't seem to be able to create PRs for wiki pages. Could I please have access to this repos wiki?

**Comment by airD173** [comment]
You know what, forget everything I said earlier. I think I'll try creating documentation on readthedocs instead.

**Comment by lykkjur** [comment]
Someone with write access to the repo can also publish proper releases (.exe, .app, etc.). Most of the code is already there and it should make it way easier for newcomers.

Not saying this should be done *instead* of proper docs, but it should definitely be done *with* it.

**Comment by airD173** [comment]
https://github.com/airD173/SpotiByeAds-Docs
Here's the (very early) documentation. It's not complete yet and I don't think I entirely understand what I'm doing but I might get it done today. HTML files can be found in /build/html.

**Comment by airD173** [comment]
I'm also requesting that you guys bear with the simplifications. I make the user install Python 3.9, which is still in the bugfix phase, and make them install the packages without the requirements.txt because things like finding a different version of Python or navigating to the program from a terminal add complexity to the install guide.

**Comment by airD173** [comment]
I have the (incomplete) docs up and running on readthedocs
https://spotibyeads.readthedocs.io/en/latest/

**Comment by ceceba223** [comment]
Are you working on the debian/ubuntu part or should i do that?

**Comment by airD173** [comment]
I was planning on using my dual boot to do it, but if you can do it that would be great @ceceba223

**Comment by ceceba223** [comment]
For debian/ubuntu python 3 can be installed by running:
`sudo apt install python3`
and that's it

**Comment by ceceba223** [comment]
Also for arch it would be:
`sudo pacman -S python3`
(even tho i believe that most people running arch know how to install python)

**Comment by AnonymouX47** [comment]
Yet to see a recent linux distro without python pre-installed... So i think anyone on linux should be safe with moving on to installing the dependencies.

**Comment by airD173** [comment]
I'll add to check for python with python3 --version. I need to boot into Ubuntu to add screenshots anyways.

**Comment by AnonymouX47** [comment]
> even tho i believe that most people running arch know how to install python

Facts...

**Comment by airD173** [comment]
I think I'm done for the most part. Before I submit a PR, can anyone add MacOS instructions to this?

**Comment by lykkjur** [comment]
I can add MacOS instructions later unless someone beats me to it in the
meantime

**Comment by airD173** [comment]
I just realized that the program automatically installs requirements.txt when it runs. I guess that simplifies installation instructions. Also, is there any specific reason it waits one second between saying it's installing and actually installing?

**Comment by AnonymouX47** [comment]
The main program should not do this.
I think it should be externally done either manually by the user or a separate script can be written for that.

Also, see #34.

**Comment by airD173** [comment]
I added back the installation instructions, but kept the note that it's optional

**Comment by daspartho** [comment]
Merged #29

**Comment by daspartho** [comment]
I couldn't thank more! This was really helpful. Now i can just reply with this to  who wants to use this. Thank you so much:D
