### ISSUE TITLE
For those who dowloaded spotify from window store.

### ISSUE THREAD

**Issue by AbhijitL** [daspartho/SpotiByeAds#2]
Just replace ```os.startfile(path)``` with ``` os.system('spotify.exe') ```  at line 11.

**Comment by WarpWing** [comment]
You could write this in a PR, I would but I don't wanna steal your thunder

**Comment by AnonymouX47** [comment]
> Just replace `os.startfile(path)` with `os.system('spotify.exe')` at line 11.

This path to the spotify executable would be incorrect except the WD is the Spotify installation directory.
