### ISSUE TITLE
Use `platform.system` instead of `os.name`

### ISSUE THREAD

**Issue by Delta456** [daspartho/SpotiByeAds#23]
https://github.com/daspartho/SpotiByeAds/blob/3efb3f91a7c9be9d0dc08e880426184ec4a55d5e/main.py#L24-L25

The above condition can be even true for Linux systems so it will be better to use `system.platform` instead.

For reference please look at this output:
![image](https://user-images.githubusercontent.com/28479139/128626840-9f7c3647-91fd-436a-b519-d3e8bca917a7.png)

and of course the explanation why to use [it](https://stackoverflow.com/a/58071295).

**Comment by AnonymouX47** [comment]
Fixed in #29, 77c0e3dd983e91424c2865e7d363b4d3c84cc03e to be precise.
