### ISSUE TITLE
Can't find spotify.exe

### ISSUE THREAD

**Issue by airD173** [daspartho/SpotiByeAds#30]
For some reason this issue from a while ago didn't submit. After putting in credentials, the program spits out an error about being unable to find spotify.exe. I checked, and my spotify executable is Spotify.exe. I'll submit a PR for this, but I'm curious about why nobody else has had this error yet. I didn't change the executable name, this is exactly how it was installed.

**Comment by airD173** [comment]
Clarification: after making the program look for Spotify.exe (capitalized) it works, which is what the PR will be about.

**Comment by airD173** [comment]
PR #31

**Comment by AnonymouX47** [comment]
> Clarification: after making the program look for Spotify.exe (capitalized) it works, which is what the PR will be about.

Ok then.

**Comment by daspartho** [comment]
Merged PR #31 should fix
