### ISSUE TITLE
Is it possible to bundle the python interpreter installer with main.py in an exe file?

### ISSUE THREAD

**Issue by import-brain** [daspartho/SpotiByeAds#34]
I tried to use PyInstaller to create an exe file from main.py, and it works fine on my main computer that has Python installed, but on my other computer which doesn't have it installed, it gives me the "pip3 not recognized" error. Is there any possible way we could bundle the python3 interpreter with the main.py file in an exe? It would make it a lot more accessible for non computer geeks.

**Comment by daspartho** [comment]
In theory pyinstaller should bundle python interpreter. Anyone got any idea what's wrong?

**Comment by AnonymouX47** [comment]
The attempted automatic installation tries to execute "pip3" command which would be unavailable on a system not having python3 installed.

Normally, the main program shouldn't even include dependency installation. It should be manually handled by the user or a separate script (probably a shell script) can be added for that.

Attempting dependency installation would be fatal on any system not having python installed.
I removed this in #29 commit https://github.com/daspartho/SpotiByeAds/pull/29/commits/2e4ce41c25f981e9fda257140d5d928cc9186995.

**Comment by AnonymouX47** [comment]
An alternative would be to bundle the 3rd-party libraries with the application but I'm not sure it's a good idea or if it'll even work properly.

**Comment by import-brain** [comment]
@AnonymouX47 @daspartho Bundling the 3rd-party libraries does seem good, but I'm surprised the PyInstaller-made exe won't recognize pip3 when it's called in the file.

**Comment by AnonymouX47** [comment]
It's trying to execute an external program... `pip` is not packaged with the program.

**Comment by daspartho** [comment]
Merged #29

**Comment by import-brain** [comment]
> Merged #29

Perfect! So I can pull changes to my fork and get pyInstaller to work now?

**Comment by AnonymouX47** [comment]
As long as you have the dependencies installed, i think PyInstaller should automatically bundle them with the application.

**Comment by AnonymouX47** [comment]
I think this discussion is better continued at #42, it's a **broader** version of this issue.
