### ISSUE TITLE
write credential inside the main folder

### ISSUE THREAD

**Issue by jedistack** [daspartho/SpotiByeAds#39]
normally the code will write a `credential.json` file to store the clientID etc aswell as a cache text file, but the files are written outside of the SpotiByeAds-main folder, it messes up your file organization and can be pretty easily fixed

in `open("./credentials.json", "r")` and `open("./credentials.json", "w")` add in `/SpotiByeAds-main` or whatever you named the file to get `open("./SpotiByeAds-main/credentials.json", "r")` for read and write respectively, now the .json file will write to a better spot

i dont know how to make the cache file write into the folder though, it's probably something on the spotify for devs side

**Comment by AnonymouX47** [comment]
How did you install it?

**Comment by airD173** [comment]
For me the .cache-username is inside the project folder.

**Comment by AnonymouX47** [comment]
The credentials JSON file is written to and loaded from the program's CWD (Current Working Directory).

So, as long as the project folder is your CWD, the credentials JSON file will be written there.
