### ISSUE TITLE
Need for a stable and standard update mechanism.

### ISSUE THREAD

**Issue by AnonymouX47** [daspartho/SpotiByeAds#40]
For those that don't use or are not used to git, updating the script after changes have been made could be clumsy.
I suggest including a script for this purpose.

I propose this following:

```
SpotiByeAds/
    ...
    update.py
    VERSION  # Will contain current version number.
```
`update.py` downloads and reads "VERSION" file from git repo to check if an update is available.
If an update is available, downloads the master zip and extracts it (using python's `zipfile`).

I did not directly open a PR, so that this can be properly discussed before implementation.

**Comment by daspartho** [comment]
That looks good to me

**Comment by AnonymouX47** [comment]
Ok then, I'll work on it and open a PR soon.

**Comment by AnonymouX47** [comment]
> Ok then, I'll work on it and open a PR soon.

I think we should wait to see how #42 goes...
