### ISSUE TITLE
TypeError : 'method' object is not subscriptable

### ISSUE THREAD

**Issue by airD173** [daspartho/SpotiByeAds#52]
An error was raised by line 71 (`time.sleep((spotify.current_user_playing_track['duration_ms']/1000) - 6) #Stop us from getting rate limited from spotify API (It just waits for the song to end)`). A quick Google search showed the fix was to replace the brackets in `spotify.current_user_playing_track['duration_ms']` with parenthesis. I'll create a PR for it.

**Comment by airD173** [comment]
Converted to a draft as it seems to break the ad blocking

**Comment by airD173** [comment]
If it means anything, I get the error `TypeError: current_user_playing_track() takes 1 positional argument but 2 were given`. As far as I can tell it only gets the argument `'duration_ms'`, so I'm not sure what could be causing it.

**Comment by AnonymouX47** [comment]
The script was broken by #48... Also see there the reason why this approach causes ads to not be skipped.

I've already opened a PR fixing the bug introduced (#50) and there's more on the "not skipping ads" issue there.
