### ISSUE TITLE
cannot open localhost8080 in firefox

### ISSUE THREAD

**Issue by Delta456** [daspartho/SpotiByeAds#57]
I cannot open localhost8080 in Mozilla Firefox on Pop OS! I am using the lastst commit.

![image](https://user-images.githubusercontent.com/28479139/129216082-b930880a-254f-473f-ae23-91978a0e7c85.png)

**Comment by AnonymouX47** [comment]
At what stage of the setup process did this occur?

**Comment by Delta456** [comment]
This happens when I start the script.

**Comment by AnonymouX47** [comment]
> This happens when I start the script.

Starting it for the first time?

**Comment by Delta456** [comment]
No it happens when I tell to use the default credentials though I have not tried clearing them and try again.

**Comment by Delta456** [comment]
No.

**Comment by AnonymouX47** [comment]
Has it ever worked?

I suspect you didn't setup the Spotify app correctly.

**Comment by Delta456** [comment]
Yes it has worked.

**Comment by AnonymouX47** [comment]
Oh, i see... so is the issue solved now?

**Comment by Delta456** [comment]
No

**Comment by AnonymouX47** [comment]
1. Go to https://developer.spotify.com/dashboard and sign in with your Spotify account.
2. Click on the 'CREATE AN APP' option and provide an app name and app description as you'd like.
3. Go to 'EDIT SETTINGS' and fill in the Redirect URIs placeholder with http://localhost:8080/, and click on Save.

Did you do step 3?

**Comment by AnonymouX47** [comment]
> No but now it is not working.

Ok, i see.

**Comment by Delta456** [comment]
>     1. Go to [https://developer.spotify.com/dashboard and](https://developer.spotify.com/dashboard%C2%A0and) sign in with your Spotify account.
> 
>     2. Click on the 'CREATE AN APP' option and provide an app name and app description as you'd like.
> 
>     3. Go to 'EDIT SETTINGS' and fill in the Redirect URIs placeholder with http://localhost:8080/, and click on Save.
> 
> 
> Did you do step 3?

Yes 
![image](https://user-images.githubusercontent.com/28479139/129252345-1fdc7c09-0032-49e8-98b1-25241f878a55.png)

**Comment by AnonymouX47** [comment]
Does your Spotify desktop app open up?

**Comment by Delta456** [comment]
Yes it opens up when I specify my own installation path else it doesn't opens up by default.

**Comment by AnonymouX47** [comment]
Try this:

**Comment by AnonymouX47** [comment]
Try this:
Within your local repo, you should see a file named like ".cache-<spotify-username>".
Delete that file.
Start the script again.

**Comment by AnonymouX47** [comment]
> Yes it opens up when I specify my own installation path else it doesn't opens up by default.

Ok, that's normal.

**Comment by Delta456** [comment]
> Try this:
> Within your local repo, you should see a file named like ".cache-".
> Delete that file.
> Start the script again.

So I did what you said. The link opens in the browser but immediately closes and if I try to access it then I get the same error. It seems like some permission was denied.

**Comment by AnonymouX47** [comment]
> So I did what you said. The link opens in the browser but immediately closes and if I try to access it then I get the same error. It seems like some permission was denied.

It's normal for the tab to close automatically... trying to access that page again (probably via your browser history will result in the error you're getting).

**Comment by Delta456** [comment]
Yes

**Comment by AnonymouX47** [comment]
> I cannot open localhost8080 in Mozilla Firefox on Pop OS! I am using the lastst commit.
> 
> ![image](https://user-images.githubusercontent.com/28479139/129216082-b930880a-254f-473f-ae23-91978a0e7c85.png)

Just to be clear... This happens when you **manually** try to access the URI right?

**Comment by Delta456** [comment]
Yes

**Comment by AnonymouX47** [comment]
> Yes

Oh... everything is fine then, 🤗.

**Comment by AnonymouX47** [comment]
> But how will I exit the script if I want to? Do I have kill the process on my own? I thought the localhost was needed to kill Spotify or the script.

A keyboard interrupt (`Ctrl-C`) is enough... for now, it's still quite messy because the exception goes unhandled but #55 will make some changes to that soon.
You could also kill the process via any means (`kill` with the appropriate PID or via a process monitor).

**Comment by Delta456** [comment]
I mean I do that but I thought it shouldn't work like that so I made an issue. Thanks for helping!

**Comment by AnonymouX47** [comment]
> I mean I do that but I thought it shouldn't work like that so I made an issue. Thanks for helping!

You're welcome.
The program doesn't exactly have an endpoint and from my experience, **CLI** programs like that (infinitely looping) have to be terminated by an external signal and since EOF is not applicable here, leaves us with `Ctrl-C`.

Anyways, i guess you could open an issue on "Exiting nicely" or a PR that adds that feature, 😃 
Thanks.

**Comment by AnonymouX47** [comment]
> I mean I do that but I thought it shouldn't work like that so I made an issue. Thanks for helping!

You're welcome.
The program doesn't exactly have an endpoint and from my experience, **CLI** programs like that (infinitely looping) have to be terminated by an external signal and since EOF is not applicable here, leaves us with `Ctrl-C`.

Anyways, i guess you could open an issue on "Exiting nicely" or a PR that adds that feature, 😃 
If you decide to do this, maybe see #55 (commit https://github.com/daspartho/SpotiByeAds/pull/55/commits/0d6519c766ad45ca7b2b24427635bca715ba16a8 especially),

Thanks.
