### ISSUE TITLE
Queue disappears aftert restart

### ISSUE THREAD

**Issue by daspartho** [daspartho/SpotiByeAds#59]
Found this thing that if i added some song in a queue to play next and an Ad comes resulting in restart, it will clear the queue.

**Comment by AnonymouX47** [comment]
I'm not sure anything much can be done about that... It's normal, the queue is always cleared when you quit the app.

**Comment by daspartho** [comment]
Yeah
If we could do something like track queue

**Comment by AnonymouX47** [comment]
`spotipy.Spotify` provides has a method for adding to the queue but i haven't seen one for reading the queue.

**Comment by airD173** [comment]
I did some Googling. As you can see [here](https://community.spotify.com/t5/Spotify-for-Developers/Spotify-Web-API-Request-GET-Queue/m-p/4968014) and [here](https://community.spotify.com/t5/Spotify-for-Developers/Spotify-Web-API-Request-GET-Queue/m-p/4968014) the web API itself doesn't have a feature to read the queue, so I don't see how Spotipy could have it.

**Comment by AnonymouX47** [comment]
@airD173 
Exactly... The best that can be done is read playlists.

**Comment by AnonymouX47** [comment]
Actually, so far, i've never had this issue. My previous queue has always been restored after a restart.

I've confirmed this on linux, i can't surely say so about Windows yet.
